### ISSUE TITLE
Build stopped when importing stylegan2_seg

### ISSUE THREAD

**Issue by AbdouMechraoui** [nv-tlabs/semanticGAN_code#17]
I am trying to run the training of `stylegan2_seg.py` , but I get the following error.

```
Traceback (most recent call last):
  File "/projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/projects/mechraoui/envs/segmentation_base/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_seg_gan.py", line 40, in <module>
    from models.stylegan2_seg import GeneratorSeg, Discriminator, MultiscaleDiscriminator, GANLoss
  File "../models/stylegan2_seg.py", line 11, in <module>
    from models.utils import *
  File "../models/utils.py", line 12, in <module>
    from models.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "../models/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "../models/op/fused_act.py", line 21, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 898, in load
    is_python_module)
  File "/projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1086, in _jit_compile
    with_cuda=with_cuda)
  File "/projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1186, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "/projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'fused': [1/2] /projects/mechraoui/envs/segmentation_base/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include/TH -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include/THC -isystem /projects/mechraoui/envs/segmentation_base/include -isystem /projects/mechraoui/envs/segmentation_base/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /projects/mechraoui/semanticGAN_code/models/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/projects/mechraoui/envs/segmentation_base/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include/TH -isystem /projects/mechraoui/envs/segmentation_base/lib/python3.6/site-packages/torch/include/THC -isystem /projects/mechraoui/envs/segmentation_base/include -isystem /projects/mechraoui/envs/segmentation_base/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /projects/mechraoui/semanticGAN_code/models/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
In file included from /projects/mechraoui/envs/segmentation_base/include/cuda_runtime.h:83,
                 from <command-line>:
/projects/mechraoui/envs/segmentation_base/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
ninja: build stopped: subcommand failed.
```

I have cuda=10.2, pytorch=1.5.0, torchvision=0.6.0, cudnn=7.6.0, and ninja=1.8.2. I noticed this issue in StyleGAN2 repo [here](https://github.com/rosinality/stylegan2-pytorch/issues/215#issue-858939004). 
May I ask which gcc version do you have? and whether you encountered this?

**Comment by AbdouMechraoui** [comment]
Closing this as I figured it out, it was an issue with cuda build environment dependencies. As the error suggests, I had to downgrade my gcc version, and link all the required libraries for cuda to build properly.
