### ISSUE TITLE
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph.

### ISSUE THREAD

**Issue by SarthakJShetty** [nv-tlabs/semanticGAN_code#24]
Thank you for open-sourcing this project! 

I was trying to train semanticGAN on our dataset (3 labels), by running:

```
python -m torch.distributed.launch --nproc_per_node=N_GPU --master_port=AVAILABLE_PORT train_seg_gan.py --img_dataset=IMG_DATASET_LOC  --seg_dataset=SEG_DATASET_LOC --inception=INCEPTION_FILE
```

(**Note**: I already updated `seg_dim` to 3 in our case in `argparse` and reduced the `color_map` to only 3 colors in `dataset.py`)

However, after the code initializates, I run into this error:

```
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior
```

Here is the entire output:

```
/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Loading unlabel dataloader with size  5
Loading unlabel dataloader with size  5
Loading train dataloader with size  4
Loading train dataloader with size  4
Loading val dataloader with size  2
Loading val dataloader with size  2
Loading unlabel dataloader with size Loading unlabel dataloader with size   55

Loading train dataloader with size  4
Loading train dataloader with size  4
Loading val dataloader with size  2
Loading val dataloader with size  2
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1303] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Traceback (most recent call last):
  File "train_seg_gan.py", line 737, in <module>
    g_optim, d_img_optim, d_seg_optim, g_ema, device, writer)
  File "train_seg_gan.py", line 386, in train
    fake_img, latents, mean_path_length
  File "train_seg_gan.py", line 111, in g_path_regularize
    outputs=(fake_img * noise).sum(), inputs=latents, create_graph=True
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/autograd/__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
Traceback (most recent call last):
  File "train_seg_gan.py", line 737, in <module>
    g_optim, d_img_optim, d_seg_optim, g_ema, device, writer)
  File "train_seg_gan.py", line 386, in train
    fake_img, latents, mean_path_length
  File "train_seg_gan.py", line 111, in g_path_regularize
    outputs=(fake_img * noise).sum(), inputs=latents, create_graph=True
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/autograd/__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
Traceback (most recent call last):
  File "train_seg_gan.py", line 737, in <module>
    g_optim, d_img_optim, d_seg_optim, g_ema, device, writer)
  File "train_seg_gan.py", line 386, in train
    fake_img, latents, mean_path_length
  File "train_seg_gan.py", line 111, in g_path_regularize
    outputs=(fake_img * noise).sum(), inputs=latents, create_graph=True
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/autograd/__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
Traceback (most recent call last):
  File "train_seg_gan.py", line 737, in <module>
    g_optim, d_img_optim, d_seg_optim, g_ema, device, writer)
  File "train_seg_gan.py", line 386, in train
    fake_img, latents, mean_path_length
  File "train_seg_gan.py", line 111, in g_path_regularize
    outputs=(fake_img * noise).sum(), inputs=latents, create_graph=True
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/autograd/__init__.py", line 236, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 113892) of binary: /home/user/anaconda3/envs/semanticGAN/bin/python
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/anaconda3/envs/semanticGAN/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_seg_gan.py FAILED
------------------------------------------------------------
```

The error seems to be in this function:

```
def g_path_regularize(fake_img, latents, mean_path_length, decay=0.01):
    noise = torch.randn_like(fake_img) / math.sqrt(
        fake_img.shape[2] * fake_img.shape[3]
    )
    grad, = autograd.grad(
        outputs=(fake_img * noise).sum(), inputs=latents, create_graph=True
    )
    path_lengths = torch.sqrt(grad.pow(2).sum(2).mean(1))

    path_mean = mean_path_length + decay * (path_lengths.mean() - mean_path_length)

    path_penalty = (path_lengths - path_mean).pow(2).mean()

    return path_penalty, path_mean.detach(), path_lengths
```

Specifically, in line 110-111 where the `grad` function is being called, on the `output` comprising of `fake_img` and `noise`, with the input being `latents`.

Please let me know if there I'm making an error while executing the command or if I need to make some more changes to the code, considering that we're trying to train on our own dataset.

Thank you for your time!

**Comment by lidaiqing** [comment]
Hi @SarthakJShetty , thank you for your interest, did you modify the original training script? do you have the same error if you run it with single gpu? Since DDP requires all the variable receiving gradients used in the loss, it will report errors if this is the case. One way to get around it is to use tensor.detach() if you do not want to use the variable.

**Comment by SarthakJShetty** [comment]
Hi @lidaiqing thank you for getting back! I made the following minior changes to the `train_seg_gan.py` script. The model does train when I train on a single GPU, but soon runs out of memory and stops. This is why we decided to train with multiple GPUs. Here are the changes that we made to the script:

1. Changed the default [here](https://github.com/nv-tlabs/semanticGAN_code/blob/main/semanticGAN/train_seg_gan.py#L574 ) from 8 to 3 (as noted above our dataset has 3 labels for the mask)
2. Included the `--local_rank` argument in the `argparse` so that `torch.distributed` can assign local rank from the environment variables.
3. To avoid running out of memory, we reduced `batch_size` to 1 in [this](https://github.com/nv-tlabs/semanticGAN_code/blob/main/semanticGAN/train_seg_gan.py#L551) line.

Apart from this we reduced the number of labels in the `color_map`  variable in `dataset.py` in [this line](https://github.com/nv-tlabs/semanticGAN_code/blob/main/dataloader/dataset.py#L97) from 8 to 3, since we have only 3 labels in the mask.

Apart from this we haven't made any changes. The data loads correctly, since we use the same organization and txt files as you have detailed in the paper/README.

Thank you for your time!

**Comment by lidaiqing** [comment]
Hi @SarthakJShetty , how much memory do you have for each GPU? I recommend at least 16G per gpu, even you can run on multi-gpus, it still requires each gpu to host one model and gradients ( no model sharing between gpu). One thing you can try is to lower your dataset resolution from 256 to 128 or 64 for debugging purpose. If you cannot run on single gpu, it is likely not working in multi-gpu as well.

**Comment by SarthakJShetty** [comment]
Thank you for getting back @lidaiqing! I think you might be right. We have 4 RTX 2080s each with 12GB. We will try running the code with reduced resolution and get back to you. However, as noted [earlier](https://github.com/nv-tlabs/semanticGAN_code/issues/24#issuecomment-1008149617), for single GPU the training does run on a single GPU but only for 1-2 iterations before running out of memory. Nonetheless we will reduce the resolution and check the training on a single GPU. Thank you.

**Comment by SarthakJShetty** [comment]
@lidaiqing Thank you for your suggestion to reduce the image size. The training does proceed on single GPU without issue. However, even with reduced image size we are not able to run the model on multiple GPUs using `torch.distributed.launch`. I wanted to know if the modifications that we made to the code, as mentioned [here](https://github.com/nv-tlabs/semanticGAN_code/issues/24#issuecomment-1008149617), would affect the performance of the distributed training? Thank you for your time!

**Comment by linyu0219** [comment]
every output must in loss compute , add 0*unuse_out[0].mean() in loss before backward

**Comment by linyu0219** [comment]
what generator output

**Comment by lidaiqing** [comment]
@SarthakJShetty does what @linyu0219 suggest solve the issues?

**Comment by SarthakJShetty** [comment]
Hi @lidaiqing, apologies for not following up on this. We were not able to get `torch.distributed` to run despite the training working without issues on a single GPU. I don't think I fullt understand @linyu0219's comment of utilizing `unuse_out`. Do they mean `d_img_loss` that is obtained from `loss_dict['d_img']`? 
For the second comment about generator output, we are able to see a random image from the `generator(noise, return_latents=True)` function.

Thank you for your time and apologies for the delay.

**Comment by linyu0219** [comment]
@SarthakJShetty 
for example 
a,b,c = generator(noise, return_latents=True)
d_img_loss = F.mse(a,b)
So you didn't use c
add c like this when use torch.distributed
d_img_loss = F.mse(a,b)+0*c[0].mean()

**Comment by theloni-monk** [comment]
Hi @SarthakJShetty, I'm trying to replicate the paper and have stumbled upon the same edits you made to the training script, but am still getting the same error as above. Which tensor exactly did you wind up having to add *0 to the d_img_loss? It says one of the diffed tensors isn't used but im confused which one its refering to.
